# Configuración del servidor para ScanDoc Pro
server.port=8080

# Conexión a Base de Datos H2 (Ideal para la entrega al instructor)
spring.datasource.url=jdbc:h2:mem:scandocdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite ver la consola de la base de datos en el navegador
spring.h2.console.enabled=true
spring.jpa.show-sql=true